IGNF/validator

- .travis.yml
- travis/build-openjdk7.sh
- travis/build-openjdk8.sh
Use jdk_switcher instead of switching between trusty or xenial
> travis - fix build using (closes #43)

- validator-core/src/main/java/fr/ign/validator/model/AttributeType.java
- validator-core/src/main/java/fr/ign/validator/xml/binding/AttributeTypeAdapter.java
- validator-core/src/main/resources/error-code.json
- validator-core/src/test/java/fr/ign/validator/xml/binding/FeatureTypeTest.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/DgprPlugin.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/database/ValidatableDatabase.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/error/DgprErrorCodes.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/process/LoadDocumentDatabasePostProcess.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/GraphTopologyValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/IdentifierValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/InclusionValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/MinMaxCoverageValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/RelationValidator.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/DgprApplicationTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/database/IdentifierValidatorTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/database/RelationValidatorTest.java
> #73 - IdentifierValidator & RelationValidator

- validator-core/src/main/java/fr/ign/validator/error/ValidatorError.java
- validator-core/src/main/resources/error-code.json
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/error/DgprErrorCodes.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/AzimuthValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/DebLinMaxValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/DebLinMinValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/DebLinValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/TauxHabitantValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/GraphTopologyValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/IdentifierValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/InclusionValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/MinMaxCoverageValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/RelationValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/ScenarioValidator.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/DgprApplicationTest.java
dev(ValidatorPluginDgpr): add scope, fileModel, feature info to database error
#76
> #76 - Attach error to feature

- validator-core/src/main/java/fr/ign/validator/data/Row.java
- validator-core/src/main/java/fr/ign/validator/validation/attribute/AttributeNullableValidator.java
- validator-core/src/main/resources/error-code.json
> avoid ATTRIBUTE_UNEXPECTED_NULL for missing columns

- validator-core/src/main/resources/error-code.json
- validator-plugin-dgpr/src/test/java/fr/ign/validator/DgprApplicationTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/attribute/DebLinMaxValidatorTest.java
et quelques descriptions supplémentaires
> Corrections typographiques messages DGPR

- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/DebLinMaxValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/DebLinMinValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/TauxHabitantValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/attribute/VitesseMinValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/MinMaxCoverageValidator.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/attribute/DebLinMaxValidatorTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/attribute/DebLinMinValidatorTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/attribute/VitesseMinValidatorTest.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/dgpr/validation/database/MinMaxCoverageValidatorTest.java
dev(ValidatorPluginDgpr): add test case for numberformatException
> validator-plugin-dgpr: fix cast error

- Makefile
- build-deb.sh
- build-rpm.sh
@floriancerizay could you try "make package" and test  `dpkg -i validator-cli/targets/*.deb`?
> build deb & rpm (closes #118)

- validator-core/src/main/resources/error-code.json
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/regress/CnigValidatorRegressTest.java
* ATTRIBUTE_CHARACTERS_REPLACED
* FILE_MISSING_RECOMMANDED
* FILE_MISSING_RECOMMANDED_DIRECTORY
* METADATA_IGNORED_FILE
* TABLE_MISSING_NULLABLE_ATTRIBUTE
> change ErrorLevel from WARNING to INFO for some errors

- validator-core/src/main/java/fr/ign/validator/Context.java
- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/GraphTopologyValidator.java
- validator-plugin-dgpr/src/test/java/fr/ign/validator/DgprApplicationTest.java
> validator-plugin-dgpr: prefix plugin parameters with --dgpr

- .travis.yml
- pom.xml
- validator-core/src/main/java/fr/ign/validator/metadata/OnlineResource.java
- validator-core/src/main/java/fr/ign/validator/metadata/gmd/MetadataISO19115.java
- validator-core/src/test/java/fr/ign/validator/metadata/gmd/MetadataISO19115Test.java
- validator-core/src/test/resources/metadata/06.xml
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/regress/CnigValidatorRegressTest.java
- validator-plugin-cnig/src/test/resources/documents-expected/110068012_PM3_28_20161104/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/172014607_AC1_2A_20180130/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/19182_CC_20150517/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/200011781_PLUi_20180101/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/30014_PLU_20171013/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/41175_PLU_20140603/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/50545_CC_20130902/document-info.json
- validator-plugin-cnig/src/test/resources/documents-expected/50545_CC_20140101/document-info.json
metadata - OnlineResource - add protocolUrl, applicationProfile and applicationProfileUrl
> Issue 146 

- CONTRIBUTING.md
- travis/build-openjdk11.sh
Easy one :
* https://github.com/IGNF/validator/blob/issue_162/travis/build-openjdk11.sh
* https://github.com/IGNF/validator/blob/issue_162/CONTRIBUTING.md#contributing
> Issue 162 - Add mvn formatter:validate to travis and help in a CONTRIBUTING.md

- LICENCE.md
http://www.cecill.info -> http://cecill.info
> fix license links (refs #171)

- validator-core/src/main/java/fr/ign/validator/data/Document.java
- validator-core/src/main/java/fr/ign/validator/database/Database.java
- validator-core/src/main/java/fr/ign/validator/model/FeatureType.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/DgprPlugin.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/process/CreateTheGeomColumn.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/GraphTopologyValidator.java
> Issue 177 - remove DGPR specific code from Database

- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
> document_validator - allow xml and json models for config,version options 

- validator-core/src/main/java/fr/ign/validator/model/type/UrlType.java
- validator-core/src/test/java/fr/ign/validator/io/JsonModelReaderTest.java
- validator-core/src/test/resources/config-json/adresse/types/ADRESSE.json
> add missing @JsonTypeName on fr.ign.validator.model.type.UrlType

- validator-core/src/main/java/fr/ign/validator/Context.java
- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
- validator-core/src/main/java/fr/ign/validator/process/DocumentInfoExtractorPostProcess.java
- validator-core/src/main/java/fr/ign/validator/process/NormalizePostProcess.java
- validator-core/src/test/java/fr/ign/validator/regress/ValidateDocumentARegressTest.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/CnigPlugin.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/DgprPlugin.java
> document_validator - add normalize option to command line

- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/tools/IdurbaFormatFactory.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/tools/IdurbaFormatSCOT.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatFactoryTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatSCOTTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatV2Test.java
> 4.0 - Fix idurba scot

- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/tools/IdurbaFormatFactory.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/tools/IdurbaFormatSCOT.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatFactoryTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatSCOTTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/tools/IdurbaFormatV2Test.java
> fix IDURBA validation for SCoT

- README.md
> travis-ci.org -> travis-ci.com (refs #208)

- validator-core/src/main/java/fr/ign/validator/error/CoreErrorCodes.java
- validator-core/src/main/java/fr/ign/validator/model/AttributeConstraints.java
- validator-core/src/main/java/fr/ign/validator/model/type/FilenameType.java
- validator-core/src/main/java/fr/ign/validator/model/type/PathType.java
- validator-core/src/main/java/fr/ign/validator/model/type/StringType.java
- validator-core/src/main/java/fr/ign/validator/model/type/UrlType.java
- validator-core/src/main/java/fr/ign/validator/validation/attribute/MinLengthValidator.java
- validator-core/src/main/resources/error-code.json
- validator-core/src/test/java/fr/ign/validator/io/JsonModelReaderTest.java
- validator-core/src/test/java/fr/ign/validator/validation/attribute/MinLengthValidatorTest.java
- validator-core/src/test/resources/config-json/adresse/types/ADRESSE.json
> validator-core - AttributeContraints - add minLength constraints 

- validator-core/src/main/java/fr/ign/validator/Context.java
- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
- validator-core/src/main/java/fr/ign/validator/command/ProjectionListCommand.java
- validator-core/src/main/java/fr/ign/validator/command/options/OutputProjectionOption.java
- validator-core/src/main/java/fr/ign/validator/command/options/StringFixerOptions.java
- validator-core/src/main/java/fr/ign/validator/data/Row.java
- validator-core/src/main/java/fr/ign/validator/error/ValidatorError.java
- validator-core/src/main/java/fr/ign/validator/exception/GeometryTransformException.java
- validator-core/src/main/java/fr/ign/validator/geometry/GeometryTransform.java
- validator-core/src/main/java/fr/ign/validator/geometry/NullTransform.java
- validator-core/src/main/java/fr/ign/validator/geometry/ProjectionList.java
- validator-core/src/main/java/fr/ign/validator/geometry/ProjectionTransform.java
- validator-core/src/main/java/fr/ign/validator/io/JsonModelReader.java
- validator-core/src/main/java/fr/ign/validator/model/Projection.java
- validator-core/src/main/java/fr/ign/validator/normalize/CSVNormalizer.java
- validator-core/src/main/java/fr/ign/validator/process/NormalizePostProcess.java
- validator-core/src/main/java/fr/ign/validator/tools/EnvelopeUtils.java
- validator-core/src/main/java/fr/ign/validator/validation/attribute/GeometryIsValidValidator.java
- validator-core/src/test/java/fr/ign/validator/command/options/OutputProjectionOptionTest.java
- validator-core/src/test/java/fr/ign/validator/geometry/ProjectionTransformTest.java
- validator-core/src/test/java/fr/ign/validator/normalize/CSVNormalizerTest.java
- validator-core/src/test/java/fr/ign/validator/process/ProjectionPreProcessTest.java
- validator-core/src/test/java/fr/ign/validator/regress/ValidateDocumentARegressTest.java
- validator-core/src/test/java/fr/ign/validator/repository/ProjectionRepositoryTest.java
- validator-core/src/test/java/fr/ign/validator/validation/database/AttributeReferenceValidatorTest.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/validation/metadata/CnigMetadataReferenceSystemIdentifierValidator.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/database/DatabaseUtils.java
- validator-plugin-dgpr/src/main/java/fr/ign/validator/dgpr/validation/database/ScenarioValidator.java
> Issue 143 - document_validator - add --output-projection

- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
- validator-core/src/main/java/fr/ign/validator/command/options/OutputFileOption.java
- validator-core/src/main/java/fr/ign/validator/command/options/ValidationDirectoryOption.java
- validator-core/src/test/java/fr/ign/validator/command/options/ValidationDirectoryOptionTest.java
> validator - document_validator - add --output option to allow to specify "validation" directory

- validator-core/src/main/java/fr/ign/validator/data/file/MultiTableFile.java
- validator-core/src/main/java/fr/ign/validator/database/Database.java
- validator-core/src/main/java/fr/ign/validator/error/CoreErrorCodes.java
- validator-core/src/main/java/fr/ign/validator/normalize/DocumentNormalizer.java
- validator-core/src/main/java/fr/ign/validator/process/CheckFeatureTypesPreProcess.java
- validator-core/src/main/java/fr/ign/validator/tools/AutoFeatureType.java
- validator-core/src/main/java/fr/ign/validator/tools/FileConverter.java
- validator-core/src/main/java/fr/ign/validator/tools/MultiTableReader.java
- validator-core/src/main/java/fr/ign/validator/tools/TableReaderOptions.java
- validator-core/src/main/resources/error-code.json
- validator-core/src/test/java/fr/ign/validator/io/JsonModelReaderTest.java
- validator-core/src/test/java/fr/ign/validator/regress/ValidatePCRSRegressTest.java
- validator-core/src/test/java/fr/ign/validator/tools/FileConverterTest.java
- validator-core/src/test/java/fr/ign/validator/tools/MultiTableReaderTest.java
> Issue 239 - Use GMLAS driver from GDAL to read GML if an xsdSchema is specified

- validator-core/src/main/java/fr/ign/validator/tools/FileConverter.java
- validator-core/src/main/resources/gdal/README.md
- validator-core/src/main/resources/gdal/gmlasconf-original.xml
- validator-core/src/main/resources/gdal/gmlasconf-validator.xml
- validator-core/src/test/java/fr/ign/validator/regress/ValidatePCRSRegressTest.java
- validator-core/src/test/java/fr/ign/validator/tools/MultiTableReaderTest.java
> Issue 241 - add experimental GMLAS_CONFIG env variable

- validator-core/src/main/resources/projection.json
> validator-core - projections.json - add support for CC42 Zone 1 to CC50 Zone 9

- validator-core/src/main/java/fr/ign/validator/command/AbstractCommand.java
- validator-core/src/test/java/fr/ign/validator/command/DocumentValidatorCommandTest.java
> fix exit code for --help command

- validator-core/src/main/java/fr/ign/validator/command/options/GeometryComplexityThresholdOption.java
- validator-core/src/main/java/fr/ign/validator/geometry/GeometryComplexityThreshold.java
- validator-core/src/main/java/fr/ign/validator/geometry/GeometryThreshold.java
- validator-core/src/test/java/fr/ign/validator/command/options/GeometryComplexityThresholdOptionTest.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/validation/attribute/GeometryComplexityValidator.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/regress/CnigValidatorRegressTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/validation/attribute/GeometryComplexityValidatorTest.java
> validator-core: update GeometryComplexityThresholdOption reader option

- validator-core/src/main/resources/error-code.json
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/CnigPlugin.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/error/CnigErrorCodes.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/model/DocumentModelName.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/validation/document/AtLeastOneAssietteValidator.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/validation/document/AtLeastOneGenerateurValidator.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/model/DocumentModelNameTest.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/regress/CnigValidatorRegressTest.java
activated only for SUP document
> validator-plugin-cnig: control at least one assiette/generateur file

- validator-core/src/main/resources/error-code.json
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/CnigPlugin.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/error/CnigErrorCodes.java
- validator-plugin-cnig/src/main/java/fr/ign/validator/cnig/validation/attribute/RegexpTxtValidator.java
- validator-plugin-cnig/src/test/java/fr/ign/validator/cnig/regress/CnigValidatorRegressTest.java
to PRESCRIPTION_SURF of PLUi model document
> validator-plugin-cnig: add Regexp attribute validation

- validator-core/src/main/java/fr/ign/validator/error/ValidatorError.java
- validator-core/src/main/java/fr/ign/validator/validation/file/XsdSchemaValidator.java
- validator-core/src/test/java/fr/ign/validator/validation/file/XsdSchemaValidatorRegressTest.java
- validator-plugin-pcrs/src/test/java/fr/ign/validator/pcrs/ValidatePcrsRegressTest.java
- validator-plugin-pcrs/src/test/resources/documents/pcrs-geovendee/LeTallud-StGemme-extrait.gml
> Issue 296 - amélioration des erreurs de validation XSD

- pom.xml
- validator-cli/pom.xml
- validator-core/pom.xml
- validator-core/src/main/java/fr/ign/validator/command/DocumentValidatorCommand.java
- validator-plugin-cnig/pom.xml
- validator-plugin-dgpr/pom.xml
- validator-plugin-pcrs/pom.xml
> Issue 299 - ajout de la version du validateur au rapport et préparation 4.4.0

- validator-core/src/main/java/fr/ign/validator/error/ValidatorError.java
- validator-core/src/main/java/fr/ign/validator/report/FilteredReportBuilder.java
- validator-core/src/test/java/fr/ign/validator/report/FilteredReportBuilderRegressTest.java
> validator-core - XSD_SCHEMA_ERROR - take xsdErrorCode in FilteredReportBuilder
